### ISSUE TITLE
Webp DMA fails with "Unable to show image due to error"

### ISSUE THREAD

**Issue by TomicekRosic** [mautrix/discord#90]
Console log shows:

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.discordapp.com/attachments/X/X/X.webp. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

>Unable to download attachment:  [rageshake.ts:72:50](webpack:///matrix-react-sdk/src/rageshake/rageshake.ts)

I noticed that changing the webp extension to png or jfif fixed it, changing a png to webp breaks it, so it only seems to care about the extension, not format. It also works on SchildiChat on phone, maybe Android Element ignores CORS?

NGINX config is directly copy pasted from https://docs.mau.fi/bridges/go/discord/direct-media.html#direct-media-access

Mautrix Discord: 0.4.0
Synapse: 1.84.0
SchildiChat Web: 1.11.30-sc.2
SchildiChat Android: 1.5.32 sc67 (problem doesn't occur here)

Thanks a lot for the project btw. The abandoned mx-puppet-bridge was becoming a pain

**Comment by tulir** [comment]
Looks like cdn.discordapp.com only provides CORS headers for specific file types rather than everything, so the redirect method for direct media access will probably just need to be discouraged. You can switch it to media.discordapp.net to make all images work, but other files won't work there either. Alternatively figure out the proxy method for nginx, that will bypass CORS issues.

Once Synapse supports following redirects as per MSC3860, you can just use the default config without any reverse proxy configuration. It'll then cache discord media in your media repo, but it can be cleaned up easily since it's remote media rather than local

**Comment by tulir** [comment]
The docs also include an nginx proxying example now

**Comment by TomicekRosic** [comment]
Alright, fair enough. I'll just wait for the MSC. Thanks
