### ISSUE TITLE
Bots trigger the `.Webhook` flag in the display name template string

### ISSUE THREAD

**Issue by HonbraDev** [mautrix/discord#94]
Given the following template string: `... [{{if .System}}DC-SYS{{else if .Webhook}}DC-WH{{else if .Bot}}DC-BOT{{else}}DC{{end}}]`, the bridge classifies regular bots as webhooks.

My workaround is to compare the `.Discriminator` value with `0000` instead - `... [{{if .System}}DC-SYS{{else if eq .Discriminator "0000"}}DC-WH{{else if .Bot}}DC-BOT{{else}}DC{{end}}]`

![bot's puppet display name changing to a webhook and me saying "my cta is not a webhook"](https://github.com/mautrix/discord/assets/54026315/7c76063e-ed45-49fd-a5dd-8a7d09dc2d4e)

**Comment by tulir** [comment]
The flag comes from Discord in the `webhook_id` field in messages (https://discord.com/developers/docs/resources/channel#message-object). Are you sure the bot isn't also a webhook?

**Comment by tulir** [comment]
Ah that makes sense, adding another field for bots that are applications shouldn't be too difficult

**Comment by Aeris1One** [comment]
Bots must respond to slash commands through a webhook automatically created for that specific interaction and isn't listed as a channel webhook, that's why it's categorized as webhook by the bot. 
It's documented under "Responding to Interactions" in Developer Docs : https://discord.com/developers/docs/interactions/receiving-and-responding#responding-to-an-interaction
